[tool.commitizen]
version = "0.1.7rc0.dev7"
bump_message = "bump: version $current_version → $new_version [skip ci]"

[tool.commitizen.customize]
bump_pattern = '^(feat|fix|build|docs|chore)(\(.+\))?(!)?'
bump_map = {"feat" = "MINOR", "fix" = "PATCH", "build" = "PATCH", "docs" = "PATCH", "chore" = "PATCH"}
