swagger: "2.0"
info:
  description: "Implementation of a RESTful interface to ClamAV."
  version: "0.0.0"
  title: "ClamAV REST"
  contact:
    email: "psypherpunk@gmail.com"
  license:
    name: "Mozilla Public License Version 2.0"
    url: "https://www.mozilla.org/media/MPL/2.0/index.815ca599c9df.txt"
host: "127.0.0.1:8000"
basePath: "/v1"
tags:
- name: "clamav"
  description: ""
  externalDocs:
    description: "Find out more about ClamAV"
    url: "https://www.clamav.net/"
schemes:
- "https"
- "http"
paths:
  /instream:
    post:
      tags:
      - "instream"
      summary: "Execute ClamAV's INSTREAM command, passing the incoming request body to ClamAV, returning the results."
      consumes:
      - "application/octet-stream"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Payload that needs to be scanned by ClamAV."
        required: true
        schema:
          type: string
          format: byte
          example: "X5O!P%@AP[4\\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*"
      responses:
        200:
          description: "successful scan"
          schema:
            $ref: "#/definitions/ApiResponse"
  /ping:
    get:
      tags:
      - "ping"
      summary: "Execute ClamAV's PING command."
      description: "Make a PING request to ClamAV. The response should be PONG."
      produces:
      - "application/json"
      responses:
        200:
          description: "successful ping"
          schema:
            $ref: "#/definitions/ApiResponse"
  /version:
    get:
      tags:
      - "version"
      summary: "Execute ClamAV's VERSION command."
      description: "Make a VERSION request to ClamAV, returning program and database versions."
      produces:
      - "application/json"
      responses:
        200:
          description: "successful ping"
          schema:
            $ref: "#/definitions/ApiResponse"
definitions:
  ApiResponse:
    type: "object"
    properties:
      output:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
