name: verify-and-update

on:
  push:
    branches:
      - '**'

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/cache@v3
        with:
          path: ~/.cache/
          key: ${{ hashFiles('requirements/test.txt') }}
      - run: python3 -m pip install --requirement requirements/test.txt
      - run: pre-commit run --all-files

  bump_version:
    runs-on: ubuntu-latest
    name: "Bump version with Commitizen"
    needs: [pre-commit]

    steps:

      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GH_PAT }}"
      
      - name: Install Commitizen
        run: |
          python3 -m pip install commitizen==2.42.1
      
      - name: Validate commits
        if: github.ref != 'refs/heads/main'
        run: |
          cz check --rev-range origin/main..

          echo "prerelease=--prerelease=rc" >>"${GITHUB_ENV}"
          echo "devrelease=--devrelease=${GITHUB_RUN_NUMBER}" >>"${GITHUB_ENV}"
      
      - id: cz
        name: Bump version
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'

          cz --name cz_customize bump --check-consistency --yes ${prerelease} ${devrelease}

          echo "version=$(cz version --project)" >> ${GITHUB_OUTPUT}
      
      - name: Push commit
        run: |
          REMOTE_REPO="https://${GITHUB_ACTOR}:${{ secrets.GH_PAT }}@github.com/${GITHUB_REPOSITORY}.git"
          git push "${REMOTE_REPO}" "HEAD:${GITHUB_REF#refs/heads/}" --tags

      - name: Print version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
